p8105_hw2_yc4585
================
2024-09-30

# Problem 2

## library

``` r
library(tidyverse)
library(readxl)
```

## import and clean data

``` r
mr_trash_wheel_df = read_excel("./202309 Trash Wheel Collection data.xlsx",
                               sheet = "Mr. Trash Wheel",skip = 1) |>
  janitor::clean_names() |>
  select(-x15,-x16) |>
  na.omit() |>
  mutate(sports_balls = round(sports_balls, 0)) |>
  mutate(sports_balls = as.integer(sports_balls))
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
professor_trash_wheel_df = read_excel("./202309 Trash Wheel Collection data.xlsx",  sheet="Professor Trash Wheel",skip = 1) |>
  janitor::clean_names() |>
  na.omit() |>
  mutate( year=as.character(year)) 

Gwynnda_trash_wheel_df = 
  read_excel("./202309 Trash Wheel Collection data.xlsx", sheet="Gwynnda Trash Wheel",
             skip = 1,na = c("NA", ".", "")) |>
  janitor::clean_names() 
```

## Combine datasets

``` r
first_trash_df=left_join(mr_trash_wheel_df,professor_trash_wheel_df,by="dumpster",
             suffix=c(".mr",".professor"))

final_trash_df=left_join(first_trash_df,Gwynnda_trash_wheel_df,by="dumpster",suffix = c("",".Gwynnda"))
```

## Calculate data

``` r
Gwynnda_June_2022=filter(Gwynnda_trash_wheel_df,month=="June"&year==2022)
sum(pull(Gwynnda_June_2022,cigarette_butts))
```

    ## [1] 18120

We can see that the data from Mr. Trash Wheel is the most comprehensive,
with a total of 584 dumpster-related entries, followed by Professor
Trash Wheel with 103 dumpster-related entries, and Gwynnda Trash Wheel
with the least, having only 38 dumpster-related entries. In the three
separate datasets, the information provided includes the dumpster
number, date, trash weight and volume, and the quantities of plastic
bottles, polystyrene, cigarette butts, glass bottles, plastic bags,
wrappers, and sports balls collected. These data allow us to clearly see
the role of the trash wheels in waste collection and environmental

The largest amount of trash collected by Mr. Trash Wheel was 5.31 tons,
and the smallest was 1.32 tons. In contrast, the largest amount of trash
collected by Professor Trash Wheel was 2.25 tons, and the smallest was
1.52 tons. This could be due to Mr. Trash Wheel’s greater trash
collection capacity, or it could be because Professor Trash Wheel is
typically deployed in areas with less trash.

From the table, we can see that the total weight of trash collected by
Professor Trash Wheel is 216.26 tons. It can be calculated that the
total number of cigarette butts collected by Gwynnda in June 2022 is
18,120.

# Problem 3

## Import and clean data

``` r
bakers_df = read_csv("./gbb_datasets/bakers.csv") |>
  janitor::clean_names() |>
  rename(baker=baker_name) |>
  mutate(baker = str_split(baker, ' ', simplify = T)[, 1])
```

    ## Rows: 120 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker Name, Baker Occupation, Hometown
    ## dbl (2): Series, Baker Age
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
bakes_df = read_csv("./gbb_datasets/bakes.csv",
                    na = c("N/A", "", ".") ) |>
                    janitor::clean_names()
```

    ## Rows: 548 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker, Signature Bake, Show Stopper
    ## dbl (2): Series, Episode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
results_df = read_csv("./gbb_datasets/results.csv",
                    skip=2,
                    na = c("NA", "", ".") ) |>
                    janitor::clean_names() |>
                    drop_na(technical,result)
```

    ## Rows: 1136 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (2): baker, result
    ## dbl (3): series, episode, technical
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

## Combine data

``` r
by=join_by(series,episode,baker)
first_combined_df=left_join(results_df,bakes_df,by)
by=join_by(series,baker)
final_conbined_df=left_join(first_combined_df,bakers_df,by)
```

When processing the bakes data, N/A values and blank spaces need to be
handled as missing values (NA). Additionally, in the baker.csv file, the
naming format in the baker name column is different from the other two
tables, as it uses full names, unlike the other two tables. Therefore,
the first name was retained during processing. In the bakes data, N/A
values and blank spaces should be considered missing values (NA). When
handling the results.csv file, N/A values and blank spaces were also
considered missing values. The first two rows, which contained no data,
were skipped, and rows where both the technical and result columns were
entirely NA were removed.

When merging datasets, the results and bakes datasets were first merged
by season, episode, and contestant name. When merging the baker data
into the already merged dataset, an issue arose where one name
corresponded to two different results in the firstdatadf. Therefore, in
addition to matching names, the series in which they participated also
had to match. In the final table, for each contestant in each season and
episode, we can determine their name, where they are from, which episode
they participated in, what bake they used, and their final result.

## Star baker&winner

``` r
star_baker=filter(results_df,(result=="STAR BAKER"|result=="WINNER")&(series>4))
```

All the winners had been Star Baker during their respective series,
except for David, whose victory in Season 10 surprised some viewers as
he had never won “Star Baker,” making him one of the less predictable
champions.

## Viewers

``` r
viewers_df = read_csv("./gbb_datasets/viewers.csv",
                      na = c("NA", "", ".") ) |>
                      janitor::clean_names()
```

    ## Rows: 10 Columns: 11
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (11): Episode, Series 1, Series 2, Series 3, Series 4, Series 5, Series ...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(viewers_df,10)
```

    ## # A tibble: 10 × 11
    ##    episode series_1 series_2 series_3 series_4 series_5 series_6 series_7
    ##      <dbl>    <dbl>    <dbl>    <dbl>    <dbl>    <dbl>    <dbl>    <dbl>
    ##  1       1     2.24     3.1      3.85     6.6      8.51     11.6     13.6
    ##  2       2     3        3.53     4.6      6.65     8.79     11.6     13.4
    ##  3       3     3        3.82     4.53     7.17     9.28     12.0     13.0
    ##  4       4     2.6      3.6      4.71     6.82    10.2      12.4     13.3
    ##  5       5     3.03     3.83     4.61     6.95     9.95     12.4     13.1
    ##  6       6     2.75     4.25     4.82     7.32    10.1      12       13.1
    ##  7       7    NA        4.42     5.1      7.76    10.3      12.4     13.4
    ##  8       8    NA        5.06     5.35     7.41     9.02     11.1     13.3
    ##  9       9    NA       NA        5.7      7.41    10.7      12.6     13.4
    ## 10      10    NA       NA        6.74     9.45    13.5      15.0     15.9
    ## # ℹ 3 more variables: series_8 <dbl>, series_9 <dbl>, series_10 <dbl>

``` r
mean(pull(viewers_df,series_1),na.rm = TRUE)
```

    ## [1] 2.77

``` r
mean(pull(viewers_df,series_5),na.rm = TRUE)
```

    ## [1] 10.0393

From above, we can know the average viewship of season 1 is 2.77, and
the viewship of season 5 is 10.0393.
